<?php

namespace Tests\Feature\Http\Controller\Category;

use App\Helpers\CategoryHelper;
use App\Models\Category;
use Database\Seeders\CategorySeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class EditCategoryControllerTest extends TestCase
{
    use WithFaker;
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed(CategorySeeder::class);
    }

    public function testAccessEditForm(){
        $category = Category::factory()->create();
        $response = $this->get(route("admin.categories.edit", $category->id));

        $response->assertStatus(200);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testUsingValidData()
    {
        $category = Category::factory()->create();

        $this->assertDatabaseHas("categories", [
            "id" => $category->id,
        ]);

        $title = $this->faker->words(3, true);

        $response = $this->from(route("admin.categories.edit", $category->id))
            ->post(route("admin.categories.update", $category->id), [
                  "title" => $title,
                "_method" => "put"
            ]);

        $this->assertDatabaseHas("categories", [
            "id" => $category->id,
            "title" => $title
        ]);

        $response->assertStatus(302);
        $response->assertRedirect(route("admin.categories.index"));
    }

    public function testUsingInvalidTitle(){
        $category = Category::factory()->create();

        $this->assertDatabaseHas("categories", [
            "id" => $category->id,
        ]);

        $title = $this->faker->unique()->words(100, true);

        $response = $this->from(route("admin.categories.edit", $category->id))
            ->post(route("admin.categories.update", $category->id), [
                "title" => $title,
                "_method" => "put"
            ]);

        $this->assertDatabaseHas("categories", [
            "id" => $category->id,
            "title" => $category->title
        ]);

        $response->assertStatus(302);
        $response->assertSessionHasErrors(["title"]);
        $response->assertRedirect(route("admin.categories.edit", $category->id));
    }

    public function testUsingNotUniqueTitle(){
        $categories = Category::factory(2)->create();

        $response = $this->from(route("admin.categories.edit", $categories[0]->id))
            ->post(route("admin.categories.update", $categories[0]->id), [
                "title" => $categories[1]->title,
                "_method" => "put"
            ]);

        $response->assertStatus(302);
        $response->assertSessionHasErrors(["title"]);
        $response->assertRedirect(route("admin.categories.edit", $categories[0]->id));
    }

    public function testAccessNotValidID(){
        $category = Category::factory()->create();

        $response = $this->get(route("admin.categories.edit", $category->id+1));

        $response->assertStatus(404);
    }

    public function testUsingNotValidID(){
        $category = Category::factory()->create();

        $response = $this->from(route("admin.categories.edit", $category->id+100))
            ->json("put", route("admin.categories.update", ($category->id+100)), [
                "title" => "invalid"
            ]);

        $response->assertStatus(404);
    }

    public function testAccessEditFormUncategorize(){
        $response = $this->get(route("admin.categories.edit", CategoryHelper::getUncategorizeID()));

        $response->assertStatus(403);
    }

    public function testEditUncategorize(){
        $id = CategoryHelper::getUncategorizeID();

        $response = $this->from(route("admin.categories.edit", $id))
            ->json("put", route("admin.categories.update", $id), [
                "title" => "new title"
            ]);

        $this->assertDatabaseMissing("categories", [
            "title" => "new title"
        ]);

        $response->assertStatus(403);
    }
}
